language: python
sudo: false
python:
  - '2.7'
install:
  - pip install -r requirements.txt --upgrade
  - pip install pytest-cov codecov
script:
  - flake8 --config=tox_tests.ini ./test/
  - flake8 --config=tox_classes.ini ./classes/
  - flake8 ./
  - python -W default::Warning -m pytest --cov=chatcommunicate --cov=findspam --cov=globalvars --cov=spamhandling --cov=datahandling test
branches:
  only:
    - master
    - travis
    - debugging
cache:
  directories:
    - $HOME/virtualenv/python2.7.9
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
  - rm -rf $HOME/.cache/pip/http
after_success:
  - codecov
