version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run:
          name: Install Python dependencies in venv
          command: |
            python3 -m venv venv
            venv/bin/pip3 install 'flake8==3.4.1'
      - run:
          name: Lint tests
          command: venv/bin/flake8 --config=tox_tests.ini ./test/
      - run:
          name: Lint classes
          command: venv/bin/flake8 --config=tox_classes.ini ./classes/
      - run:
          name: Lint code
          command: venv/bin/flake8 ./
  test:
    docker:
      - image: circleci/python:3.6-stretch
    steps:
      - checkout
      - run:
          name: Install Python dependencies in venv
          command: |
            python3 -m venv venv
            venv/bin/pip3 install -r requirements.txt --upgrade
            venv/bin/pip3 install -r user_requirements.txt --upgrade
      - run:
          name: Pytest
          command: venv/bin/python3 -W default::Warning -m pytest test

workflows:
  version: 2
  lint_and_test:
    jobs:
      - lint
      - test
